---
# This configuration is used to deploy NCM, upload OVAs & Images in Management PC.
# Deploy PC VMs in the PEs specified in clusters

# Global variables, which can be inherited in blocks
pc_creds: &pc_creds
  # This can be admin/ ad user. Note ad creds will be used after adding AD to PC
  pc_username: pc-user
  pc_password: pc-password
  # New admin password for PC
  admin_pc_password: admin-pc-password

pe_creds: &pe_creds
  # This can be admin/ ad user. Note ad creds will be used after adding AD to PE
  pe_username: pe-user
  pe_password: pe-password

cvm_creds: &cvm_creds
  # This will be nutanix user used to login to CVM CLI
  cvm_username: nutanix
  cvm_password: nutanix/4u

deploy_pc_file_urls: &deploy_pc_file_urls
  # Files to deploy PC in PE. PC software tar file, its metafile & pc_version are required to download & upload software to PE
  file_url: https://url-to-download-pc-xxxx.x.x.tar
  metadata_file_url: https://url-to-download-metadata.json
  pc_version: pc.xxxx.x.x
  # md5sum of the PC tar file used to compare after file is downloaded. This is optional
  md5sum: md5sum-of-pc-xxxx.x.x.tar-file

pod:
  pod_name: "pod_east"
  pc_ip: valid-ip
  <<: *pc_creds
  ovas:
    # OVAs that needs to be uploaded to the PC clusters
    - url: http://url-to-download-ova-from # url where the ova file is located
      name: ova-name # name of the ova to be uploaded to the PC clusters
      cluster_name_list: [cluster-1, cluster-2] # cluster names to upload ovas. We can upload to multiple clusters

  images:
    # Images that needs to be uploaded to the PC clusters
    - url: http://url-to-download-image-from # url where the image file is located
      name: image-name # name of the image to be uploaded to the PC clusters
      image_type: DISK_IMAGE # image type that is uploaded. Allowed values: DISK_IMAGE, ISO_IMAGE
      cluster_name_list: [cluster-1, cluster-2] # cluster names to upload images. We can upload to multiple clusters

  ncm:
    # Deploy NCM in PC clusters. The below config supports deployment of multiple NCM accross multiple clusters
    - cluster_name: cluster-1 # PC Cluster name to deploy NCM
      ova_name: calm-vm-pc-xxxx-calm-x.x.x.ova # Calm VM OVA to deploy from
      vm_spec_list:
      - vm_name: vm-name1 # NCM VM name
        subnet_name: vlan-1 # Subnet to use for VM deployment
    - cluster_name: cluster-2 # PC Cluster name to deploy NCM
      ova_name: calm-vm-pc-xxxx-calm-x.x.x.ova # Calm VM OVA to deploy from
      vm_spec_list:
      - vm_name: vm-name2 # NCM VM name
        subnet_name: vlan-2 # Subnet to use for VM deployment

  # BCDR Clusters where the PC is deployed
  clusters:
    valid-cluster-01-ip:
        # Use global pe creds
        <<: *pe_creds
        # Use global cvm creads
        <<: *cvm_creds

        # Config required to deploy PC in PE
        deploy_pc_config:
          # Use global deploy pc files urls config
          <<: *deploy_pc_file_urls
          pc_vm_name_prefix: MGMT-PC  # PC VM name prefix, numbers will be added to the name based on number of pc vms Eg: MGMT-PC-0
          num_pc_vms: 3 # Number of PC vms to deploy i.e Single PC (1) or Scale-out-PC(3). Allowed values: 1, 3
          pc_size: large # Size of the PC VM. Based on the size the VM spec will be used. Allowed values: [small, large, xlarge]
          pc_vip: x.x.x.x # PC VIP Address
          ip_list: [x.x.x.x, x.x.x.x, x.x.x.x] # IP addresses for PC VMs. Depends on the number of PC VMs
          ntp_server_list: [ntp-server1, ntp-server2] # List of NTP Servers to be added to PC VMs.
          dns_server_ip_list: [dns-server-ip1, dns-server-ip2] # List of DNS Server IP addresses to be added to PC VMs.
          container_name: SelfServiceContainer # Container in which the VMs need to be created
          network_name: MGMTVLAN0 # Subnet to use for PC VM creation
          default_gateway: x.x.x.1 # Subnet gateway
          subnet_mask: 255.255.255.0 # Subnet mask
          delete_existing_software: false # Delete the software with same version if it already exists in PE
    valid-cluster-02-ip:
      # Use global pe creds
        <<: *pe_creds
        # Use global cvm creads
        <<: *cvm_creds

        # Config required to deploy PC in PE
        deploy_pc_config:
          # Use global deploy pc files urls config
          <<: *deploy_pc_file_urls
          pc_vm_name_prefix: MGMT-PC  # PC VM name prefix, numbers will be added to the name based on number of pc vms Eg: MGMT-PC-0
          num_pc_vms: 3 # Number of PC vms to deploy i.e Single PC (1) or Scale-out-PC(3). Allowed values: 1, 3
          pc_size: large # Size of the PC VM. Based on the size the VM spec will be used. Allowed values: [small, large, xlarge]
          pc_vip: x.x.x.x # PC VIP Address
          ip_list: [x.x.x.x, x.x.x.x, x.x.x.x] # IP addresses for PC VMs. Depends on the number of PC VMs
          ntp_server_list: [ntp-server1, ntp-server2] # List of NTP Servers to be added to PC VMs.
          dns_server_ip_list: [dns-server-ip1, dns-server-ip2] # List of DNS Server IP addresses to be added to PC VMs.
          container_name: SelfServiceContainer # Container in which the VMs need to be created
          network_name: MGMTVLAN0 # Subnet to use for PC VM creation
          default_gateway: x.x.x.1 # Subnet gateway
          subnet_mask: 255.255.255.0 # Subnet mask
          delete_existing_software: false # Delete the software with same version if it already exists in PE
