pc_ip: valid-pc-ip
# Specify a user with permission to make API calls.
pc_credential: pc_user # credential reference from "vaults" in global.yml file

vms:
  - name: image-name 
    cluster_name: cluster-name 
  - name: image-name
    cluster_name: cluster-name