pe_creds: &pe_creds
  # Specify a user with permission to make API calls.
  pe_credential: pe_user # credential reference from "vaults" in global.yml file
  # below parameter is needed if we are updating default password for "admin"
  new_pe_admin_credential: admin_cred # credential reference from "vaults" in global.yml file

cluster_eula: &eula
  eula:
    username: Nutanix
    company_name: Nutanix
    job_title: Backend Engineer

pulse: &pulse
  enable_pulse: true

clusters:
  # configure the below clusters in the site
  valid-cluster-01-ip:
    # Use global pe creds
    <<: *pe_creds
    # Use global eula config
    <<: *eula
    # Use global pulse config
    <<: *pulse
  valid-cluster-02-ip:
    # can be defined locally as well
    pe_credential: pe_user # credential reference from "vaults" in global.yml file
    # below parameter is needed if we are updating default password for "admin"
    new_pe_admin_credential: admin_cred # credential reference from "vaults" in global.yml file

    eula:
      username: Nutanix1
      company_name: Nutanix
      job_title: Backend Engineer

    enable_pulse: false
