pc_ip: valid-pc-ip
# Specify a user with permission to make API calls.
pc_credential: pc_user # credential reference from "vaults" in global.yml file


remote_azs:
  # If remote AZs are referred in protection rules, they have to be first declared here
  valid-remote-pc-ip:
    pc_credential: remote_pc_credentials # credential reference from "vaults" in global.yml file

#Create
protection_rules:
  - name: AZ01-AZ02-Calm
    desc: "Example Protection Rule for CalmAppliance"
    protected_categories:
      AppType:
        - CalmAppliance
    schedules:
      - source:
          # Source should always be Local AZ i.e local block PC
          availability_zone: valid-local-block-pc-ip
          clusters:
            - source-cluster1 # regional BCDR cluster1
            - source-cluster2 # regional BCDR cluster2
        destination:
          availability_zone: valid-local-block-pc-ip/valid-remote-pc-ip
          cluster: destination-cluster
        protection_type: ASYNC # ASYNC/ SYNC
        # if protection_type is SYNC
        #auto_suspend_timeout: 10
        # if protection_type is ASYNC
        rpo: 1
        rpo_unit: HOUR # MINUTE/HOUR/DAY/WEEK
        snapshot_type: "CRASH_CONSISTENT" # APPLICATION_CONSISTENT/CRASH_CONSISTENT
        local_retention_policy:
          # For Linear Retention type (Retains the n most recent snapshots. A value of 12 means that the 12 most recent snapshots are retained)
          num_snapshots: 1
          # For Roll-up retention type (Maintains a rolling window of snapshots for every schedule, starting with the hourly schedule and ending with the schedule created for the specified retention period)
#          rollup_retention_policy:
#            snapshot_interval_type: YEARLY # DAILY/WEEKLY/MONTHLY/YEARLY
#            multiple: 2
        remote_retention_policy:
          # For Linear Retention type
          num_snapshots: 1
          # For Roll-up retention type

#          rollup_retention_policy:
#            snapshot_interval_type: YEARLY # HOURLY/DAILY/WEEKLY/MONTHLY/YEARLY
#            multiple: 2

#Delete
protection_rules:
  - name: AZ01-AZ02-Calm


######################################## SCHEMA DOCUMENTATION ########################################
### 			---CREATE SCHEMA --- 			 ###

# protection_rules:
#   type: list
#   required: false
#   schema:
#     type: dict
#     schema:
#       name:
#         type: string
#         required: true
#       desc:
#         type: string
#       protected_categories:
#         type: dict
#         required: true
#         keyschema:
#           type: string
#         valueschema:
#           type: list
#       schedules:
#         type: list
#         required: true
#         schema:
#           type: dict
#           schema:
#             source:
#               schema:
#                 availability_zone:
#                   type: string
#                   required: true
#                 clusters:
#                   type: list
#                   required: true
#             destination:
#               type: dict
#               required: true
#               schema:
#                 availability_zone:
#                   type: string
#                   required: true
#                 cluster:
#                   type: string
#                   required: true
#             protection_type:
#               type: string
#               required: true
#               allowed:
#               - ASYNC
#               - SYNC
#             rpo:
#               type: integer
#               required: true
#             rpo_unit:
#               type: string
#               required: true
#               allowed:
#               - MINUTE
#               - HOUR
#               - DAY
#               - WEEK
#             snapshot_type:
#               type: string
#               required: true
#               allowed:
#               - CRASH_CONSISTENT
#               - APPLICATION_CONSISTENT
#             local_retention_policy:
#               type: dict
#               schema:
#                 num_snapshots:
#                   type: integer
#                 rollup_retention_policy:
#                   type: dict
#                   required: false
#                   schema:
#                     snapshot_interval_type:
#                       type: string
#                       required: true
#                       allowed:
#                       - HOURLY
#                       - DAILY
#                       - WEEKLY
#                       - MONTHLY
#                       - YEARLY
#                     multiple:
#                       type: integer
#                       required: true
#             remote_retention_policy:
#               type: dict
#               schema:
#                 num_snapshots:
#                   type: integer
#                 rollup_retention_policy:
#                   type: dict
#                   required: false
#                   schema:
#                     snapshot_interval_type:
#                       type: string
#                       required: true
#                       allowed:
#                       - HOURLY
#                       - DAILY
#                       - WEEKLY
#                       - MONTHLY
#                       - YEARLY
#                     multiple:
#                       type: integer
#                       required: true
# 


### 			---DELETE SCHEMA --- 			 ###

# protection_rules:
#   type: list
#   required: false
#   schema:
#     type: dict
#     schema:
#       name:
#         type: string
# 

####################################################################################################
