pc_ip: valid-pc-ip
# Specify a user with permission to make API calls.
pc_credential: pc_user # credential reference from "vaults" in global.yml file

pe_creds: &pe_creds
  # Specify a user with permission to make API calls.
  pe_credential: pe_user # credential reference from "vaults" in global.yml file

clusters:
  # configure the below clusters in the site
  valid-cluster-01-ip:
    # Use global pe creds for authentication
    <<: *pe_creds
  valid-cluster-02-ip:
    # can be defined locally as well
    pe_credential: pe_user # credential reference from "vaults" in global.yml file
  valid-cluster-03-ip:
    # Use global pe creds for authentication
    <<: *pe_creds