pc_ip: valid-pc-ip
# Specify a user with permission to make API calls.
pc_credential: pc_user # credential reference from "vaults" in global.yml file

#Create
service_groups:
  - name: ngt
    description: Example Service Group NGT - TCP
    service_details:
      tcp:
        - "2074"
        - "22-30" # Give in this format for range of ports
      icmp:
        - code: 1 #Code can be in Range 0-43
          type: 8 #Type Can be in Range 0-15
        - code: 2
          type: 9
  - name: dns
    description: Example Service Group DNS - UDP
    service_details:
      udp:
        - "53"
      any_icmp: true # If true, ICMP will be allowed for all types of ICMP

#Delete
service_groups:
  - name: ngt
  - name: dns


######################################## SCHEMA DOCUMENTATION ########################################
### 			---CREATE SCHEMA --- 			 ###

# service_groups:
#   type: list
#   schema:
#     type: dict
#     schema:
#       name:
#         type: string
#         required: true
#       description:
#         type: string
#       service_details:
#         type: dict
#         required: true
#         keyschema:
#           type: string
#         valueschema:
#           type: list
# 


### 			---DELETE SCHEMA --- 			 ###

# service_groups:
#   type: list
#   schema:
#     type: dict
#     required: true
#     schema:
#       name:
#         type: string
# 

####################################################################################################
