name: Backend workflow calls to trigger Python framework

on:
  workflow_call:
    inputs:
      file:
        type: string
        required: true
      branch:
        type: string
        required: true
      workflow:
        type: string
        required: false
      pr_user:
        type: string
        required: true
      approved_user:
        type: string
        required: true

jobs:
  create-python-environment:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        #  gives you either a new virtualenv, or restores an old one based on
        #  the requirements*.txt -file.
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: "**/requirements/*.in"
    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      with:
        requirement_files: "**/requirements/*.in"
      # the package installation will only be executed when the
      # requirements*.txt - file has changed.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        pip-compile --output-file=requirements/dev.txt requirements/dev.in 
        pip install -r requirements/dev.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
  run-python-workflow:
    needs: create-python-environment
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Restore cache
        uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: "**/requirements/*.in"
      - name: Run python script
        shell: bash
        run: |
          echo "PR_CREATED_BY: " ${{ inputs.pr_user }} > commit.log
          echo "PR_APPROVED_BY: " ${{ inputs.approved_user }} >> commit.log
          python main.py --workflow ${{ inputs.workflow }} --file ${{ inputs.file }}
      - name: Git add config and logs
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "Workflow trigger logs"
      - name: Push the config and logs to the trigger branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ inputs.branch }}
